spec: 
  ports:
    - name: prom
      protocol: TCP 
      port: 9779
      targetPort: 9779
  template:
    spec:
      ports:
      - name: prom
        protocol: TCP 
        port: 9779
        targetPort: 9779
      containers:
        - name: config
          env:
            - name: AB_JOLOKIA_OFF
              value: true
            - name: JAVA_OPTIONS 
              value: -javaagent:/deployments/agent-bond-agent-1.0.2.jar=jolokia{{port=8778}},jmx_exporter{{9779:config.yml}}
            - name: JAVA_APP_JAR
              value: grpc-sb-camel-server-1.0.0.jar
